name: Calculator Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install Python Dependencies
        run: uv sync --reinstall

      - name: Create docs directory structure
        run: mkdir -p docs/python docs/cpp

      - name: Build Python docs
        run: uv run pdoc calculator.py -o docs/python

      - name: Build C++ docs with Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: './Doxyfile'

      - name: Verify docs structure
        run: |
          echo "Contents of docs directory:"
          ls -la docs/
          echo "Contents of docs/python directory:"
          ls -la docs/python/ || echo "python directory not found"
          echo "Contents of docs/cpp directory:"
          ls -la docs/cpp/ || echo "cpp directory not found"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4